##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: deploy.yml
##
---

# Prepare the physical environment
- ansible.builtin.import_playbook: playbooks/01-preparePhysical.yml

# Deploy nested vSphere
- ansible.builtin.import_playbook: playbooks/02-deployVc.yml
- ansible.builtin.import_playbook: playbooks/03-prepareISOInstaller.yml
- ansible.builtin.import_playbook: playbooks/04-deployNestedEsxi.yml

- ansible.builtin.import_playbook: playbooks/05-configureNestedEsxi.yml
- ansible.builtin.import_playbook: playbooks/06-createVds.yml
- ansible.builtin.import_playbook: playbooks/07-configureVsan.yml
- ansible.builtin.import_playbook: playbooks/08-license_vSphere.yml


# Deploy NSX-T
- ansible.builtin.import_playbook: playbooks/11-deployNsxManager.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
 
- ansible.builtin.import_playbook: playbooks/12-license_NSXT-LM.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/13-registerNsxComputeManager.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/14-createNsxTz.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/15-createNsxIpPool.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/16-createNsxUplinkProfiles.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/17-createNsxTnp.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/18-attachNsxTnp.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/19-createNsxEdgeTn.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Product.NSXT.Edge == true

- ansible.builtin.import_playbook: playbooks/20-createNsxEdgeCluster.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Product.NSXT.Edge == true


  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Setting.IPv6 == true

- ansible.builtin.import_playbook: playbooks/21-createNsxVLANSegments.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true

- ansible.builtin.import_playbook: playbooks/22-createNsxT0Gateway.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Product.NSXT.Edge == true

- ansible.builtin.import_playbook: playbooks/23-createNsxT1Gateway.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Product.NSXT.Edge == true

- ansible.builtin.import_playbook: playbooks/24-createNsxOverlaySegments.yml
  when: 
    - Deploy.Product.NSXT.LocalManager == true
    - Deploy.Product.NSXT.Edge == true

