##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: deploynestedInfra.yml
##
---

# Prepare the physical environment
- ansible.builtin.import_playbook: playbooks/01-preparePhysical.yml

# Deploy nested vSphere
- ansible.builtin.import_playbook: playbooks/02-deployVc.yml
- ansible.builtin.import_playbook: playbooks/03-prepareISOInstaller.yml
- ansible.builtin.import_playbook: playbooks/04-deployNestedEsxi.yml

- ansible.builtin.import_playbook: playbooks/05-configureNestedEsxi.yml
- ansible.builtin.import_playbook: playbooks/06-createVds.yml
- ansible.builtin.import_playbook: playbooks/07-configureVsan.yml
- ansible.builtin.import_playbook: playbooks/08-license_vSphere.yml
