##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: undeploy.yml
##
---
- hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
    - answerfile.yml 
  name: undeploy.yml
  tasks:
    - name: Remove Physical ESXi Host to vCSA for SDDC Lab deployment
      community.vmware.vmware_host:
        hostname: "{{ Nested_vCenter.FQDN | lower }}"
        username: "{{ Nested_vCenter.User }}"
        password: "{{ Nested_vCenter.Password }}"
        datacenter_name: "{{ Nested_vCenter.DataCenter }}"
        cluster_name: "{{ Target.Physical_Cluster }}"
        validate_certs: false
        esxi_hostname: "{{ Target.FQDN }}"
        esxi_username: "{{ Target.User }}"
        esxi_password: "{{ Target.Password }}"
        state: absent
      async: 7200
      poll: 0        
    - name: Remove ESXi VMs for Cluster-A
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ item.value.VMName }}"
        force: true
        state: absent
      async: 7200
      poll: 0
      loop: "{{ Nested_ESXi.HostCA | dict2items }}"
      ignore_errors: true
    - name: Remove ESXi VMs for Cluster-B
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ item.value.VMName }}"
        force: true
        state: absent
      async: 7200
      poll: 0
      loop: "{{ Nested_ESXi.HostCB | dict2items }}"
      ignore_errors: true

    - name: Remove vCenter VM
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_vCenter.VMName }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Remove NSX Manager VM(s)
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ Nested_NSXT.Components.LocalManager.VMName }}"
        force: true
        state: absent
      ignore_errors: true
    - name: Remove NSX EDGE VM-1
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: vSDDC-T0-EdgeVM-01
        force: true
        state: absent
      ignore_errors: true
    - name: Remove NSX EDGE VM-2
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: vSDDC-T0-EdgeVM-02
        force: true
        state: absent
      ignore_errors: true

    - name: Remove NSXT EDGE VM(s)
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ item.value.Name }}"
        force: true
        state: absent
      ignore_errors: true
      with_dict: "{{ AVI.Cluster }}"

    - name: Remove AVI VM(s)
      community.vmware.vmware_guest:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: no
        name: "{{ item.value.Name }}"
        force: true
        state: absent
      ignore_errors: true
      with_dict: "{{ AVI.Cluster }}"