##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/preparePhysical.yml
##    Purpose: This Ansbile script is to prepare the physical environment, which includes:
##              a) Creating vSphere Switch (vDS or vSS)
##              b) Creating vSphere Port-Groups (Mgmt and Trunk)
##              c) VM Folder Structure (vCenter Deployment Only)
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml    
  name: preparePhysical.yml
  tasks:
    - name: preparePhysical_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"

##
###############################################################################################################
##                                    vSphere Standard Switch Deployment                                     ##
##                                        Target.Deployment == "Host"                                        ##
###############################################################################################################
##


    - name: Create a VMware vSphere Standard Switch (vSS) on the ESXi host
      community.vmware.vmware_vswitch:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        nics:
#        -  vmnic0            #Add the uplink name assign to this vSwitch
        -  vmnic1            #delete the second uplink if have a single physical nic
        mtu: 9000
        state: present
      register: vss_result
      when: Target.Deployment == "Host"

    - name: DEBUG -- Display vss_result
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          =================================================================================================
          Variable: vss_result
          ====================
          {{ vss_result | to_nice_yaml }}
          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Target.Deployment == "Host"

    - name: Create a management port group for the lab environment
      community.vmware.vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false        
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.Management.Name }}"
        vlan_id: "{{ Target.PortGroup.Management.VLAN }}"
        security:
          promiscuous_mode: True
      when: Target.Deployment == "Host"

    - name: Create trunk port group for the lab environment
      community.vmware.vmware_portgroup:
        hostname: "{{ Target.FQDN }}"
        username: "{{ Target.User }}"
        password: "{{ Target.Password }}"
        validate_certs: false
        esxi_hostname: "{{ Target.FQDN }}"
        switch_name: "{{ Target.vSwitch }}"
        portgroup_name: "{{ Target.PortGroup.Trunk.Name }}"
        vlan_id: "{{ Target.PortGroup.Trunk.VLAN }}"
        security:
          promiscuous_mode: True
          forged_transmits: True
          mac_changes: True
      when: Target.Deployment == "Host"


##
## Permit things to stablize
##

    - name: Wait 5 seconds for the Port Groups to become available
      ansible.builtin.pause: seconds=5
