##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/deployNsxManager.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml    
  name: deployNsxManager.yml
  tasks:
    - name: deployNsxManager_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"
    - name: Check if NSX-T Local Manager is already installed
      ansible.builtin.uri:
        url: https://{{ NSXT.Components.LocalManager.FQDN }}
        validate_certs: False
        timeout: 5
      register: nsxman_check
      ignore_errors: true
      failed_when: false
      no_log: true
      when: Deploy.Product.NSXT.LocalManager == true


    - name: Deploy NSX-T Local Manager from OVA when deployment options is Host
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ vCenter.FQDN }}"
        username: "{{ vCenter.User }}"
        password: "{{ vCenter.Password }}"
        validate_certs: no
        datastore: "{{ Target.DatastoreSSD }}"
        allow_duplicates: no
#        folder: "{% if Target.Deployment == 'vCenter' %}/{{ Target.DataCenter }}/vm/{{ Target.VMFolder }}{% else %}{{ Target.VMFolder }}{% endif %}"         # For vCenter deployment, VM Folder path must be the FULL path: /<DataCenter>/vm/<ParentFolder>/<ChildFolder>
        datacenter: "{{ Target.DataCenter }}"
        cluster: "{{ Target.Physical_Cluster }}"
        name: "{{ NSXT.Components.LocalManager.VMName }}"
        ovf:  "{{ Deploy.Software.NSXT.Directory }}/{{ Deploy.Software.NSXT.File }}"
        deployment_option: "{{ NSXT.Components.LocalManager.Deployment.Size }}"
        networks:
          "Network 1": "{{ vCenter.Networking.Physical.PortGroup.Management.Name }}"
        disk_provisioning: "{{ Common.DiskProvisioning }}"
        power_on: yes
        fail_on_spec_warnings: yes
        wait: yes
        wait_for_ip_address: yes
        inject_ovf_env: yes
        properties:
          nsx_cli_audit_username: "{{ NSXT.Credential.audit.Name }}"
          nsx_cli_audit_passwd_0: "{{ NSXT.Credential.audit.Password }}"
          nsx_cli_username: "{{ NSXT.Credential.admin.Name }}"
          nsx_cli_passwd_0: "{{ NSXT.Credential.admin.Password }}"
          nsx_allowSSHRootLogin: "{{ NSXT.Components.LocalManager.Deployment.EnableSSH }}"
          nsx_isSSHEnabled: "{{ NSXT.Components.LocalManager.Deployment.EnableSSH }}"
          nsx_dns1_0: "{{ Common.DNS.Server1.IPv4 }}"
          nsx_domain_0: "{{ Common.DNS.Domain }}"
          nsx_gateway_0: "{{ NSXT.Components.LocalManager.Address.IPv4.Gateway }}"
          nsx_hostname:  "{{ NSXT.Components.LocalManager.FQDN }}"
          nsx_ip_0:      "{{ NSXT.Components.LocalManager.Address.IPv4.Address }}"
          nsx_netmask_0: "{{ (NSXT.Components.LocalManager.Address.IPv4.Address + '/' + NSXT.Components.LocalManager.Address.IPv4.Prefix) | ipaddr('netmask') }}"
          nsx_ntp_0:     "{{ Common.NTP.Server1.IPv4 }}"
          nsx_passwd_0:  "{{ NSXT.Credential.admin.Password }}"
          nsx_role:      "{{ NSXT.Components.LocalManager.Deployment.Role }}"
      delegate_to: localhost
      when:
        - Deploy.Product.NSXT.LocalManager == true
        - Target.Deployment == "Host"
        - nsxman_check.status != 200
      async: 7200
      poll: 0
      register: deployment

    - name: Wait 600 seconds before start checking whether the NSX-T Manager node is ready
      ansible.builtin.pause: seconds=600
      when: 
        - Deploy.Product.NSXT.LocalManager == true
        - deployment.changed == true
        - nsxman_check.status != 200

    - name: Result check for NSX-T Manager node deployment
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      with_items: "{{ deployment.results }}"
      when:
        - Deploy.Product.NSXT.LocalManager == true
        - deployment.changed == true
        - item.started is defined

    - name: Wait until the NSX-T API reports that the NSX-T Manager cluster is "STABLE"
      ansible.builtin.uri:
        url: https://{{ NSXT.Components.LocalManager.FQDN | lower }}/api/v1/cluster/status
        validate_certs: no
        timeout: 5
        force_basic_auth: yes
        url_username: "{{ NSXT.Credential.admin.Name }}"
        url_password: "{{ NSXT.Credential.admin.Password }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      register: result
      until: result.status == 200 and result.json.detailed_cluster_status.overall_status == "STABLE"
      retries: 20
      delay: 60
      when: 
        - Deploy.Product.NSXT.LocalManager == true
    - name: Write annotation on the NSX-T Local Manager VM when Target Deployment is Host
      community.vmware.vmware_guest:
        hostname: "{{ vCenter.FQDN }}"
        username: "{{ vCenter.User }}"
        password: "{{ vCenter.Password }}"
        validate_certs: no
        cluster: "{{ Target.Physical_Cluster }}"
        datacenter: "{{ Target.DataCenter }}"
        folder: "{{ Target.VMFolder }}"
        name: "{{ NSXT.Components.LocalManager.VMName }}"
        annotation: | 
                    {{ Common.Annotation }}
                    {{ Deploy.Software.NSXT.Vendor }} {{ Deploy.Software.NSXT.Product}} {{ Deploy.Software.NSXT.Version }}
                    Username: {{ NSXT.Credential.admin.Name }}
                    Password: {{ NSXT.Credential.admin.Password }}
      when: 
        - Deploy.Product.NSXT.LocalManager == true
        - Target.Deployment == "Host"

##
## Disable Password Expiration for all users except for root (API does not permit disabling for 'root' user)
##
    - name: Obtain NSX-T Local Manager User List
      ansible.builtin.uri:
        url: https://{{ NSXT.Components.LocalManager.FQDN | lower }}/api/v1/node/users
        validate_certs: no
        timeout: 15
        force_basic_auth: yes
        url_username: "{{ NSXT.Credential.admin.Name }}"
        url_password: "{{ NSXT.Credential.admin.Password }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      register: UserList
      when: 
        - Deploy.Product.NSXT.LocalManager == true

    - name: Disable Password Expiration Of All NSX-T Users (except for 'root')
      ansible.builtin.uri:
        url: https://{{ NSXT.Components.LocalManager.FQDN | lower }}/api/v1/node/users/{{ item.userid }}
        validate_certs: no
        timeout: 15
        force_basic_auth: yes
        url_username: "{{ NSXT.Credential.admin.Name }}"
        url_password: "{{ NSXT.Credential.admin.Password }}"
        method: PUT
        body_format: json
        body: '{ "password_change_frequency": 0 }'
        return_content: yes
        status_code: 200
      loop: "{{ UserList.json.results }}"
      when: 
        - Deploy.Product.NSXT.LocalManager == true
        - item.userid > 0
