##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/registerNsxComputeManager.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml 
  name: registerNsxComputeManager.yml
  tasks:
    - name: registerNsxComputeManager_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"


    - name: Register NSX-T Compute Manager
      nsxt_fabric_compute_managers:
          hostname: "{{ NSXT.Components.LocalManager.FQDN }}"
          username: "{{ NSXT.Credential.admin.Name }}"
          password: "{{ NSXT.Credential.admin.Password }}"
          validate_certs: False
          display_name: "{{ vCenter.VMName }}"                 # Using VMName as no need for full domain
          server: "{{ vCenter.FQDN }}"
          origin_type: vCenter
          credential:
            credential_type: UsernamePasswordLoginCredential
            username: "{{ vCenter.User }}"
            password: "{{ vCenter.Password }}"
          state: present
#      when: Deploy.Product.NSXT.LocalManager == true
#      async: 1800
#      poll: 0
