##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/createNsxTz.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml   
  name: createNsxTz.yml
  tasks:
    - name: createNsxTz_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"


    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ============================= Display Variables For Pod {{Pod.Name}} ============================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

                                          Target.FQDN: {{ Target.FQDN }}
                                          Target.User: {{ Target.User }}
                                      Target.Password: {{ Target.Password }}
                                       Target.Cluster: {{ Target.Cluster }}
                                    Target.DataCenter: {{ Target.DataCenter }}
                                     Target.Datastore: {{ Target.Datastore }}
                                      Target.VMFolder: {{ Target.VMFolder }}

             NSXT.Components.LocalManager.FQDN: {{ NSXT.Components.LocalManager.FQDN }}

              NSXT.System.Fabric.TransportZone: {{ NSXT.System.Fabric.TransportZone }}

              NSXT.System.Fabric.TransportZone: {{ NSXT.System.Fabric.TransportZone | dict2items }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Create NSX-T transport zones
      nsxt_transport_zones:
        hostname: "{{ NSXT.Components.LocalManager.FQDN }}"
        username: "{{ NSXT.Credential.admin.Name }}"
        password: "{{ NSXT.Credential.admin.Password }}"
        validate_certs: False
        resource_type: "TransportZone"
        display_name: "{{ item.key }}"
        is_default: "{{ item.value.SetAsDefault }}"
        description: "{{ item.value.Description }}"
        transport_type: "{{ item.value.Type }}"
        #host_switch_name: "{{ item.value.Switch }}"
        #host_switch_mode: "STANDARD"
        state: present
      register: result
      loop: "{{ NSXT.System.Fabric.TransportZone | dict2items }}"
      when:
        - Deploy.Product.NSXT.LocalManager == true
