##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/createNsxUplinkProfiles.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml  
  name: createNsxUplinkProfiles.yml
  vars:
    LOCAL_UplinkProfiles_Template: "{{ Target.TemplateFolder }}/vars_NSXT_UplinkProfiles.j2"
  tasks:
    - name: createNsxUplinkProfiles_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"

    - name: Get list of Uplink Profiles
      ansible.builtin.set_fact:
        UplinkProfilesToCreate: "{{ lookup('template', LOCAL_UplinkProfiles_Template) | from_yaml }}"
      when: Deploy.Product.NSXT.LocalManager == true

    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display UplinkProfilesToCreate Variable ===================================

              UplinkProfilesToCreate: {{ UplinkProfilesToCreate | to_nice_yaml(indent=2) }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.Product.NSXT.LocalManager == true
        - UplinkProfilesToCreate != ""

    - name: Create Uplink Profiles
      nsxt_uplink_profiles:
        hostname: "{{ NSXT.Components.LocalManager.FQDN }}"
        username: "{{ NSXT.Credential.admin.Name }}"
        password: "{{ NSXT.Credential.admin.Password }}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"                              # Description
        transport_vlan: "{{ item.transport_vlan }}"                        # Overlay Transport VLAN
        teaming: "{{ item.teaming }}"                                      # Default NIC Teaming
        named_teamings: "{{ item.named_teamings | default(omit) }}"        # Named Teaming Policy, but omit it if it does not exist
        state: "present"
      with_list: "{{ UplinkProfilesToCreate }}"
      when:
        - Deploy.Product.NSXT.LocalManager == true
        - UplinkProfilesToCreate != ""
