##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/createNsxEdgeCluster.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml 
  name: createNsxEdgeCluster.yml
  vars:
      LOCAL_EdgeClusterTemplate: "{{ Target.TemplateFolder }}/vars_NSXT_EdgeClusters.j2"
  tasks:

    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ Pod.Name }} ==================================


                                            Ansible Playbook: {{ ansible_play_name }}

                                           Target.Deployment: {{ Target.Deployment }}

                    NSXT.Components.LocalManager.FQDN: {{ NSXT.Components.LocalManager.FQDN }}

          NSXT.System.Fabric.Nodes.EdgeTransportNodes: {{ NSXT.System.Fabric.Nodes.EdgeTransportNodes }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.Product.NSXT.LocalManager == true

    - name: Read the structure from template into a variable
      ansible.builtin.set_fact:
        var_EdgeClusters: "{{ lookup('template', LOCAL_EdgeClusterTemplate) | from_yaml }}"
      when:
        - Deploy.Product.NSXT.LocalManager == true
        - Deploy.Product.NSXT.Edge == true

    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display var_EdgeClusters Variable ===================================

              var_EdgeTransportNodes: {{ var_EdgeClusters | to_nice_yaml(indent=2) }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.Product.NSXT.LocalManager == true
        - var_EdgeClusters != ""


    - name: Create NSX-T Edge Cluster
      nsxt_edge_clusters:
        hostname: "{{ NSXT.Components.LocalManager.FQDN }}"
        username: "{{ NSXT.Credential.admin.Name }}"
        password: "{{ NSXT.Credential.admin.Password }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        tags: "{{ item.tags }}"
        cluster_profile_bindings: "{{ item.cluster_profile_bindings }}"
        members: "{{ item.members }}"
        state: present
      register: edge_cluster
      loop: "{{ var_EdgeClusters }}"
      when: 
        - Deploy.Product.NSXT.LocalManager == true
        - Deploy.Product.NSXT.Edge == true
        - var_EdgeClusters != ""

    - name:  Wait until the NSX-T API reports that the Edge Cluster is in realized state
      ansible.builtin.uri:
        url: https://{{ NSXT.Components.LocalManager.FQDN }}/policy/api/v1/infra/sites/default/enforcement-points/default/edge-clusters/{{ edge_cluster | json_query('results[].id') | first }}
        validate_certs: no
        timeout: 5
        force_basic_auth: yes
        url_username: "{{ NSXT.Credential.admin.Name }}"
        url_password: "{{ NSXT.Credential.admin.Password }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 60
      when: 
        - Deploy.Product.NSXT.LocalManager == true
        - Deploy.Product.NSXT.Edge == true
        - var_EdgeClusters != ""