##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/createNsxVLANSegments.yml
##
---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml 
  name: createNsxVLANSegments.yml
  vars:
      LOCAL_Segments_Template: "{{ Target.TemplateFolder }}/vars_NSXT_Segments.j2"
  tasks:
    - name: createNsxVLANSegments_Playbook
      ansible.builtin.debug:
        msg: "Starting playbook: {{ ansible_play_name }}"

    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display Variables For Pod {{ Pod.Name }} ==================================


                                     Ansible Playbook: {{ ansible_play_name }}

                                    Target.Deployment: {{ Target.Deployment }}

             Nested_NSXT.Components.LocalManager.FQDN: {{ Nested_NSXT.Components.LocalManager.FQDN }}

                      Nested_NSXT.Networking.Segments: {{ Nested_NSXT.Networking.Segments }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true

    - name: Get list of Segments
      ansible.builtin.set_fact:
        SegmentsToCreate: "{{ lookup('template', LOCAL_Segments_Template) | from_yaml }}"
      when: Deploy.Product.NSXT.LocalManager == true

    - name: DEBUG -- Display Target Variables (Pause)
      ansible.builtin.pause:
        seconds: "{{ DEBUG.DisplayDelayInSeconds }}"
        prompt: |
          ================================ Display SegmentsToCreate Variable ===================================

              SegmentsToCreate: {{ SegmentsToCreate | to_nice_yaml(indent=2) }}

          =================================================================================================
      when:
        - DEBUG.DisplayVariables == true
        - Deploy.Product.NSXT.LocalManager == true
        - SegmentsToCreate != ""

    ## Create only VLAN-backed Segments in SegmentsToCreate  ##
    - name: Create NSX-T Segments
      nsxt_policy_segment:
        hostname: "{{ Nested_NSXT.Components.LocalManager.FQDN }}"
        username: "{{ Nested_NSXT.Credential.admin.Name }}"
        password: "{{ Nested_NSXT.Credential.admin.Password }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description:  "{{ item.description }}"
        admin_state:  "{{ item.admin_state }}"
        replication_mode: "{{ item.replication_mode }}"
        transport_zone_display_name: "{{ item.transport_zone_display_name }}"
        tags: "{{ item.tags }}"
        vlan_ids: "{{ item.vlan_ids }}"
        state: "present"
      loop: "{{ SegmentsToCreate }}"
      when: 
      - Deploy.Product.NSXT.LocalManager == true
      - Nested_NSXT.System.Fabric.TransportZone[item.transport_zone_display_name].Type == "VLAN"
