##
##    Project: VMware NSXT SDDC Design POC Lab
##    Authors: VirtualSachIN
##    Filename: playbooks/34-createCloudUser.yml
##
---
- hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
    - ../answerfile.yml 
  name: Create cloud  users for cloud connecter
  tasks:
    - name: Create NSXT user credentials to  connect NSXT Cloud
      vmware.alb.avi_api_session:
        avi_credentials: "{{ AVI.credentials }}"
        http_method: post
        path: "cloudconnectoruser"
        data:
          nsxt_credentials:
              username: "{{ NSXT.Credential.admin.Name }}"
              password: "{{ NSXT.Credential.admin.Password }}"
          name: "{{ NSXT.Components.LocalManager.FQDN  }}"

    - name: Create vCenter user credentials to  connect VMware vCenter/ESXi Cloud
      vmware.alb.avi_api_session:
        avi_credentials: "{{ AVI.credentials }}"
        http_method: post
        path: "cloudconnectoruser"
        data:
          vcenter_credentials:
              username: "{{ vCenter.User }}"
              password: "{{ vCenter.Password }}"
          name: "{{ vCenter.FQDN }}"

    - name: Check existing Policy_API_Endpoint
      uri:
        url: "https://{{ NSXT.Components.LocalManager.FQDN }}/policy/api/v1/infra/sites/default/enforcement-points/alb-endpoint"
        url_username: "{{ NSXT.Credential.admin.Name | default(omit) }}"
        url_password: "{{ NSXT.Credential.admin.Password | default(omit) }}"
        method: GET
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body: AviConnectionInfo
      register: policy_api
      ignore_errors: yes
    - debug:
           msg: "{{policy_api.status}}"
    - name: Create Policy_API_Endpoint
      uri:
        url: "https://{{ NSXT.Components.LocalManager.FQDN }}/policy/api/v1/infra/sites/default/enforcement-points/alb-endpoint"
        url_username: "{{ NSXT.Credential.admin.Name | default(omit) }}"
        url_password: "{{ NSXT.Credential.admin.Password | default(omit) }}"
        method: GET
        force_basic_auth: yes
        validate_certs: no
        body_format: "{{item}}"
        body: "{{ lookup('template', 'enforcement_point.json.j2')}}"
      register: policy_api
      with_items:
      - "{{nsxt.method}}"
      when: policy_api.status == 404 or nsxt.force_update == 1