

---

- hosts: localhost
  connection: local
  vars_files:
  - ../answerfile.yml 
  tasks:
    - name: Check existing Policy_API_Endpoint
      uri:
        url: "https://{{ Nested_NSXT.Components.LocalManager.FQDN }}/policy/api/v1/infra/sites/default/enforcement-points/alb-endpoint"
        url_username: "{{ Nested_NSXT.Credential.admin.Name | default(omit) }}"
        url_password: "{{ Nested_NSXT.Credential.admin.Password | default(omit) }}"
        method: GET
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body: AviConnectionInfo
      register: policy_api
      ignore_errors: yes
    - debug:
           msg: "{{policy_api.status}}"
    - name: Create Policy_API_Endpoint
      uri:
        url: "https://{{ Nested_NSXT.Components.LocalManager.FQDN }}/policy/api/v1/infra/sites/default/enforcement-points/alb-endpoint"
        url_username: "{{ Nested_NSXT.Credential.admin.Name | default(omit) }}"
        url_password: "{{ Nested_NSXT.Credential.admin.Password | default(omit) }}"
        method: GET
        force_basic_auth: yes
        validate_certs: no
        body_format: "{{item}}"
        body: "{{ lookup('template', 'enforcement_point.json.j2')}}"
      register: policy_api
